pull_request_rules:
  - name: automatic merging of greenkeeper pulls
    conditions:
      - author=greenkeeper[bot]
      - label~=greenkeeper
      - label!=WIP
      - label!=waiting
    actions:
      merge:
        method: merge
        strict: true
  - name: automatic merging when label is set
    conditions:
      - label!=WIP
      - label!=waiting
      - label~=ready to merge
    actions:
      merge:
        method: merge
        strict: true
  - name: delete merged branches
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: add WIP label when WIP is in title
    conditions:
      - title~=WIP
    actions:
      message: Please remove WIP from the title. We have set the WIP Label for you instead.
      label:
        add:
          - WIP
