branches:
  only:
    - stable
    - master
language: node_js
node_js:
  - lts/*
dist: xenial
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
jobs:
  include:
    # Lint
    - stage: run parallel
      script: yarn lint:ci
      name: "lint"
    # Test
    - script:
        - yarn test:ci
        - codecov
      name: "test"
      install:
        - yarn global add codecov
    # Build & Deploy
    - script: yarn build
      name: "build"
      install:
        - yarn global add surge
      services:
        - docker
      sudo: required
      # deploy
      after_success: bash ./deploy/pull-deploy.sh
      deploy:
        skip_cleanup: true
        provider: script
        script: bash ./deploy/deploy.sh
        on:
          branch: master
cache: yarn
before_cache:
  # delete all .cache folders before actually storing the cache.
  # nuxt, storybook and vuepress stores some build artefacts here which invalidates the cache.
  - cd $TRAVIS_BUILD_DIR/node_modules && find . -name .cache -type d -exec rm -r {} +
notifications:
  email: false
