branches:
  only:
    - stable
    - master
language: node_js
node_js:
  - lts/*
sudo: required
dist: xenial
services:
  - docker
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
    - SC_THEME=default
install:
  - yarn global add codecov surge
  - yarn install --production=false
jobs:
  include:
    - stage: prepare cache
      script: true
    # Lint
    - stage: lint
      script: yarn lint:all:eslint
      name: "eslint"
    - script: yarn lint:all:stylelint
      name: "stylelint"
    - script: yarn lint:all:markdownlint
      name: "markdownlint"
    - script: yarn lint:all:prettier
      name: "prettier"
    # Test
    - stage: test
      script: yarn test:unit:ci
      name: "unit"
    # Build
    - stage: build
      script: yarn build:nuxt
      name: "nuxt"
      deploy:
        skip_cleanup: true
        provider: script
        script: bash ./deploy/deploy.sh nuxt
        on:
          branch: master
    - script: yarn build:docs
      name: "docs"
      after_success: bash ./deploy/pull-deploy.sh docs
      deploy:
        skip_cleanup: true
        provider: script
        script: bash ./deploy/deploy.sh docs
        on:
          branch: master
    - script: yarn build:storybook
      name: "storybook"
      after_success: bash ./deploy/pull-deploy.sh storybook
      deploy:
        skip_cleanup: true
        provider: script
        script: bash ./deploy/deploy.sh storybook
        on:
          branch: master
stages:
  - prepare cache
  - lint
  - test
  - build
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
