branches:
  only:
    - stable
    - master
language: node_js
node_js:
  - lts/*
dist: xenial
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
    - SC_THEME=default
jobs:
  include:
    # Warmup Cache
    - stage: prepare cache
      name: "warmup cache"
      script: true
    # Lint
    - stage: run parallel
      script: yarn lint:ci
      name: "lint"
    # Test
    - script:
        - yarn test
        - codecov
      name: "test"
      install:
        - yarn global add codecov
    # Build & Deploy
    - script: yarn build
      name: "build"
      install:
        - yarn global add surge
      services:
        - docker
      sudo: required
      # deploy
      after_success: bash ./deploy/pull-deploy.sh
      deploy:
        skip_cleanup: true
        provider: script
        script: bash ./deploy/deploy.sh
        on:
          branch: master
stages:
  - prepare cache
  - run parallel
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
