branches:
  only:
    - stable
    - master
language: node_js
node_js:
  - lts/*
dist: xenial
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
jobs:
  include:
    # Lint
    - stage: run parallel
      script: yarn lint:ci
      name: "lint"
    # Test
    - script:
        - yarn test
        - codecov
      name: "test"
      install:
        - yarn global add codecov
    # Build & Deploy
    - script: yarn build
      name: "build"
      install:
        - yarn global add surge
      services:
        - docker
      sudo: required
      # deploy
      after_success: bash ./deploy/pull-deploy.sh
      deploy:
        skip_cleanup: true
        provider: script
        script: bash ./deploy/deploy.sh
        on:
          branch: master
cache:
  yarn: true
  directories:
    - node_modules
before_cache:
  # delete the .cache folder before actually storing the cache.
  # storybook stores some build artefacts here which potentialy invalidates the cache.
  - rm -rf $TRAVIS_BUILD_DIR/node_modules/.cache
notifications:
  email: false
