branches:
  only:
    - develop
    - master
language: node_js
node_js:
  - lts/*
dist: xenial
git:
  submodules: false
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
jobs:
  include:
    # Build & Deploy
    - stage: run parallel
      script: npm run build
      name: "build"
      install:
        - npm i -g surge
      services:
        - docker
      sudo: required
      # deploy
      after_success: bash ./deploy/pull-deploy.sh
      deploy:
        skip_cleanup: true
        provider: script
        script: bash ./deploy/deploy.sh
        on:
          all_branches: true
    # Test
    - script:
        - npm run test:ci
        - codecov
      name: "test"
      install:
        - npm i -g codecov
    # Lint
    - script: npm run lint:ci
      name: "lint"

cache: npm
before_cache:
  # delete all .cache folders before actually storing the cache.
  # nuxt, storybook and vuepress stores some build artefacts here which invalidates the cache.
  - cd node_modules && find . -name .cache -type d -exec rm -rf {} + && cd ..
  - cd node_modules && find . -name .temp -type d -exec rm -rf {} + && cd ..
notifications:
  email: false
