language: node_js
node_js:
  - lts/*
sudo: required
dist: xenial
services:
  - docker
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
    - SC_THEME=default
    - API_HOST=http://localhost:3030
before_install:
  - openssl aes-256-cbc -K $encrypted_b7461320c5f4_key -iv $encrypted_b7461320c5f4_iv -in deploy/travis_rsa.enc -out deploy/travis_rsa -d
install:
  - yarn global add codecov
  - yarn install --production=false
script:
  - yarn ci
  - codecov
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
notifications:
  email: false
cache:
  directories:
    - node_modules
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy/deploy.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master$
  # deploy storybook for all pull requests
  - provider: surge
    skip_cleanup: true
    project: ./dist/storybook/
    domain: stories.$TRAVIS_PULL_REQUEST.nuxt.schul-cloud.surge.sh
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST AND $TRAVIS_BRANCH != master
  # deploy docs for all pull requests
  - provider: surge
    skip_cleanup: true
    project: ./dist/storybook/
    domain: docs.$TRAVIS_PULL_REQUEST.nuxt.schul-cloud.surge.sh
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST AND $TRAVIS_BRANCH != master
