name: Test

on: [push]

jobs:
  test-unit:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: npm ci
        run: npm ci
      - name: npm run test:unit
        run: npm run test:ci
      - name: codecov
        run: |
          npm i -g codecov
          codecov
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: npm ci
        run: npm ci
      - name: npm run lint
        run: npm run lint
