name: Test

on: [push]

jobs:
  test-unit:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: npm ci
        run: npm ci
      - name: npm run test:unit
        run: npm run test:ci
      - name: codecov
        run: npx codecov
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: npm ci
        run: npm ci
      - name: npm run lint
        run: npm run lint
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        theme: [default, brb, n21, open]
    runs-on: ${{ matrix.platform }}
    env:
      SC_THEME: ${{ matrix.theme }}
    steps:
      - uses: actions/checkout@v1
      - name: npm ci
        run: npm ci
      - name: npm run build:nuxt
        run: npm run build:nuxt
